const candyData = [
  { "id": 1, "name": "Song of Bernadette, The", "type": 6 },
  { "id": 2, "name": "Pan", "type": 1 },
  { "id": 3, "name": "Street Fighter: Assassin's Fist", "type": 5 },
  { "id": 4, "name": "Guilty as Sin", "type": 3 },
  { "id": 5, "name": "Crank", "type": 3 },
  { "id": 6, "name": "Rio 2", "type": 2 },
  { "id": 7, "name": "Callas Forever", "type": 2 },
  { "id": 8, "name": "Luxo Jr.", "type": 4 },
  { "id": 9, "name": "Gentlemen Don't Eat Poets (Grotesque, The)", "type": 5 },
  { "id": 10, "name": "Alien Cargo", "type": 6 },
  { "id": 11, "name": "Tube Tales", "type": 1 },
  { "id": 12, "name": "Ace of Hearts, The", "type": 5 },
  { "id": 13, "name": "Work of Director Michel Gondry, The", "type": 3 },
  { "id": 14, "name": "Finding Nemo", "type": 5 },
  { "id": 15, "name": "Lost Youth", "type": 5 },
  { "id": 16, "name": "Human Planet", "type": 2 },
  { "id": 17, "name": "Sky Fighters (Les Chevaliers Du Ciel)", "type": 2 },
  { "id": 18, "name": "When Willie Comes Marching Home", "type": 1 },
  { "id": 19, "name": "Turtle's Tale: Sammy's Adventures, A", "type": 5 },
  { "id": 20, "name": "Frankie and Alice", "type": 6 },
  { "id": 21, "name": "Land Before Time, The", "type": 1 },
  { "id": 22, "name": "Aqua Teen Hunger Force Colon Movie Film for Theaters", "type": 6 },
  { "id": 23, "name": "What's in a Name (Prénom, Le)", "type": 4 },
  { "id": 24, "name": "Jesus Christ Superstar", "type": 1 },
  { "id": 25, "name": "Blood Alley", "type": 2 },
  { "id": 26, "name": "Adventures of Prince Achmed, The (Abenteuer des Prinzen Achmed, Die)", "type": 5 },
  { "id": 27, "name": "Noise", "type": 1 },
  { "id": 28, "name": "Kill Theory", "type": 3 },
  { "id": 29, "name": "Virginity Hit, The", "type": 5 },
  { "id": 30, "name": "Nanny McPhee Returns (a.k.a. Nanny McPhee and the Big Bang)", "type": 1 },
  { "id": 31, "name": "Prime of Miss Jean Brodie, The", "type": 4 },
  { "id": 32, "name": "City of Ember", "type": 3 },
  { "id": 33, "name": "Fingersmith", "type": 3 },
  { "id": 34, "name": "Goke, Body Snatcher from Hell (Kyuketsuki Gokemidoro)", "type": 3 },
  { "id": 35, "name": "Match Point", "type": 2 },
  { "id": 36, "name": "Another Me", "type": 1 },
  { "id": 37, "name": "Tale of Despereaux, The", "type": 3 },
  { "id": 38, "name": "Patterns", "type": 6 },
  { "id": 39, "name": "Bliss", "type": 2 },
  { "id": 40, "name": "Tru Confessions", "type": 2 },
  { "id": 41, "name": "Cremator, The (Spalovac mrtvol)", "type": 3 },
  { "id": 42, "name": "Restaurant", "type": 5 },
  { "id": 43, "name": "Poolhall Junkies", "type": 3 },
  { "id": 44, "name": "The Ghosts in Our Machine", "type": 3 },
  { "id": 45, "name": "MURDER and murder", "type": 6 },
  { "id": 46, "name": "Unknown Woman, The (La Sconosciuta)", "type": 4 },
  { "id": 47, "name": "Alarmist, The (a.k.a. Life During Wartime)", "type": 4 },
  { "id": 48, "name": "O'Horten", "type": 6 },
  { "id": 49, "name": "I Love Your Work", "type": 5 },
  { "id": 50, "name": "Star Trek III: The Search for Spock", "type": 1 }
]

export default candyData